#!/bin/bash


echo Unpack Bibledit-release
cd
cd Desktop
rm -rf chromified
mkdir chromified
cd chromified
unzip ../Bibledit-release


echo Add a copy of field “name” and name it "short_name"
sed -i.bak '/extName/a\
"short_name": "__MSG_extName__",\
' manifest.json
sed -i.bak 's/\"short/\  "short/g' manifest.json


VERSION=`grep version_name manifest.json | sed 's/^.*: //' | sed -e 's/"\(.*\)"\,/\1/'`
echo Update field “version” to $VERSION
sed -i.bak "s/\0\.76/$VERSION/g" manifest.json


echo Remove 3D and WebGL requirements


# Remove sed .bak file.
rm manifest.json.bak


echo ZIP the directory
zip -r ../Bibledit.zip .


echo Bibledit.zip is ready for upload
