#!/bin/bash

# Set the SDK root.
export NACL_SDK_ROOT=~/scr/nacl_sdk/pepper_49

# Run the Makefile
make $@

# Copy output into place.
FILE=pnacl/Release/bibledit.pexe
[[ -e $FILE ]] && cp $FILE .
FILE=pnacl/Release/bibledit.nmf
[[ -e $FILE ]] && cp $FILE .
