#!/bin/bash

# Set the SDK root.
export NACL_SDK_ROOT=~/scr/nacl_sdk/pepper_49

# Clean previous output.
FILE=pnacl/Release/bibledit.pexe
[[ -e $FILE ]] && rm $FILE

# Build through Makefile.
make $@

# Copy output into place.
FILE=bibledit.pexe
[[ -e $FILE ]] && rm $FILE
FILE=pnacl/Release/bibledit.pexe
[[ -e $FILE ]] && cp $FILE .
FILE=pnacl/Release/bibledit.nmf
[[ -e $FILE ]] && rm $FILE
FILE=pnacl/Release/bibledit.nmf
[[ -e $FILE ]] && cp $FILE .
